name: CI/CD Testing Pipeline
'on':
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs: 
  test_and_build:
    environment: Test Enviornment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: testsecret
        run: |
          if [ -z "$DATABASEURL" ]; then
            echo "DATABASEURL is undefined"
          else
            echo "DATABASEURL is defined (but hidden)"
          fi
      - name: Install Dependencies
        run: bun install
        env:
          AdminPassword: ${{ secrets.ADMINPASSWORD }}
          AdminEmail: ${{ secrets.ADMINEMAIL }}
          DatabaseURL: ${{ secrets.DATABASEURL }}
          TestUserEmail: ${{secrets.TESTUSEREMAIL}}
          TestUserPassword: ${{secrets.TESTUSERPASSWORD}}
      - name: Run Backend Tests
        run: bun run dev --test
