name: CI/CD Testing Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs: 
  test_and_build:
    environment: Test Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install Dependencies
        run: bun install

      - name: Start Backend Server in Background
        run: bun run src/index.ts & # Or replace with your actual server command
        env:
          AdminPassword: ${{ secrets.ADMINPASSWORD }}
          AdminEmail: ${{ secrets.ADMINEMAIL }}
          DatabaseURL: ${{ secrets.DATABASEURL }}
          TestUserEmail: ${{ secrets.TESTUSEREMAIL }}
          TestUserPassword: ${{ secrets.TESTUSERPASSWORD }}

      - name: Wait for Server to Be Ready
        run: |
          echo "Waiting for server to be ready..."
          for i in {1..10}; do
            if curl --silent http://localhost:8080 | grep -q "OK"; then
              echo "Server is up!"
              break
            fi
            sleep 2
          done

      - name: Run Backend Tests
        run: bun test
        env:
          TestUserEmail: ${{ secrets.TESTUSEREMAIL }}
          TestUserPassword: ${{ secrets.TESTUSERPASSWORD }}
